### ISSUE TITLE
No conflicts but can not send backports

### ISSUE THREAD

**Issue by yp05327** [GiteaBot/gitea-backporter#119] opened 2024-02-20 08:13 UTC
<made a mistake, so the old comment was deleted, see the comment below>

**Comment by yp05327** [comment] 2024-02-20 08:15
There are two PRs of mine:
https://github.com/go-gitea/gitea/pull/29190
https://github.com/go-gitea/gitea/pull/29173

**Comment by silverwind** [comment] 2024-02-20 16:01
Sounds like duplicate of https://github.com/GiteaBot/gitea-backporter/issues/110.

**Closed** 2024-02-22 00:44 UTC
